run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gosec
    - revive
  disable:
    - depguard

linters-settings:
  goimports:
    local-prefixes: github.com/aallbrig/treemand
  revive:
    rules:
      - name: exported
        disabled: false
  gosec:
    excludes:
      - G304  # file path from variable (acceptable for CLI tools)
      - G204  # subprocess launched with variable (expected for discovery)

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
